namespace: code-server

nameOverride: ""

commonLabels:
  app: code-server

serviceAccount:
  create: false
  name: ""

auth:
  usePassword: true
  existingSecret: ""
  password: code321

deploy:
  image:
    registry: docker.io
    repository: massipssa/coder-server
    tag: 0.0.1
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPorts:
    http: 8080
  resources:
    limits: {}
    requests: {}

service:
  ports:
    http: 8080
  port: 80
  targetPort: 8080


ingress:
  enabled: true
  ingressClassName: ""
  hostname: coder.local
  pathType: Prefix
  path: /

pvc:
  existingPvc: ""
  accessMode: ReadWriteOnce
  storage: 1Gi