apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: code-server
  name: {{ include "coder.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: {{ .Values.deploy.replicaCount }}
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: {{ include "coder.name" . }}
        imagePullPolicy: {{ .Values.deploy.image.pullPolicy | quote }}
        image: {{ include "coder.image" . }}
        ports:
        - containerPort: {{ .Values.deploy.containerPorts.http }}
        env:
          {{- if .Values.auth.usePassword }}
          - name: PASSWORD
            valueFrom: 
              secretKeyRef: 
                name:  {{ include "coder.secretName" . }}
                key: password
          {{- end}}
        volumeMounts:
        - name: pv-code-server
          mountPath: /config

        {{- if .Values.deploy.resources }}
        resources: {{- toYaml .Values.deploy.resources | nindent 12 }}
        {{- end }}
      volumes:
      - name: pv-code-server
        persistentVolumeClaim:
          claimName: pvc-code-server   