apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: {{ include "coder.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: {{ .Values.deploy.replicaCount }}
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: "{{ .Values.deploy.image.repository }}/{{ .Values.deploy.image.name }}:{{ .Values.deploy.image.tag }}"
        imagePullPolicy: {{ .Values.deploy.image.pullPolicy | quote }}
        name: {{ include "coder.name" . }}
        ports:
        - containerPort: {{ .Values.deploy.containerPorts.http }}
        env:
          {{- if  ".Values.auth.usePassword" }}
          - name: PASSWORD
            value: {{ .Values.auth.password }}
          {{- end}}
        {{- if .Values.deploy.resources }}
        resources: {{ - toYaml .Values.web.resources | nindent 12 }}
        {{- end }}