apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: {{ include "coder.name" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: "{{ .Values.deploy.image.repository }}/{{ .Values.deploy.image.name }}:{{ .Values.deploy.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: code-server
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: PASSWORD
          value: "code321"