{{- if .Values.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coder.name" . }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  password: {{ .Values.auth.password | b64enc | quote }} 
{{- end -}}