apiVersion: v1
kind: Service
metadata:
 name: {{ include "coder.name" . }}
 namespace:  {{ .Release.Namespace | quote }}
spec:
 ports:
 - name: http
   protocol: TCP
   port: {{ .Values.service.port }}
   targetPort: {{ .Values.service.targetPort }}
 selector:
   app: code-server